// <auto-generated />
namespace DataBaseCommunication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mt5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mt5));
        
        string IMigrationMetadata.Id
        {
            get { return "202101041218100_mt5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
